# Generated by Django 5.2.6 on 2025-09-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="conversation",
            old_name="conversation_id",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="message",
            old_name="message_id",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="user_id",
            new_name="id",
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
    ]
